---
- name: install build ruby package
  yum: name={{item}} state=installed
  with_items:
  - ruby-devel
  - rubygems

- name: install rubyenv
  become: no
  args:
    ## guard for only once.
    creates: ~/.rbenv
  shell: |
    git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
    ## add rbenv env
    (
        echo 'export RBENV_ROOT=~/.rbenv'
        echo 'export PATH=$RBENV_ROOT/bin:$PATH'
        echo 'eval "$(rbenv init -)"'
        echo ''
    ) >> ~/.bashrc
    source ~/.bashrc
    # install ruby
    git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
    rbenv install {{ruby.version}}
