---
- name: check rbenv
  stat: path=/etc/profile.d/rbenv.sh
  register: rbenv_sh

- name: get rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=/usr/local/rbenv
  when: not rbenv_sh.stat.exists

- name: get ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=/usr/local/rbenv/plugins/ruby-build
  when: not rbenv_sh.stat.exists

- name: copy global profile for rbenv
  copy: src=rbenv.sh dest=/etc/profile.d/rbenv.sh
  when: not rbenv_sh.stat.exists

- name: check ruby
  shell: /bin/bash -lc "rbenv versions | grep {{ ruby.version }}"
  register: ruby_installed
  failed_when: ruby_installed.rc not in [0, 1]

- name: remove old ruby
  yum: name={{ item }} state=absent
  with_items:
    - ruby
    - ruby-devel
  when: ruby_installed|failed

- name: install packages
  yum: name={{ item }} state=present
  with_items:
    - openssl
    - openssl-devel
    - readline
    - readline-devel
  when: ruby_installed|failed

# use login shell
# see http://qiita.com/FGtatsuro/items/2366c93131c47aef8dfe
# see https://github.com/ansible/ansible/issues/4854
- name: install ruby
  shell: /bin/bash -lc "rbenv install {{ ruby.version }} && rbenv rehash && rbenv global {{ ruby.version }}"
  when: ruby_installed|failed
