---
- name: install goenv
  become: no
  args:
    ## guard for only once.
    creates: ~/.goenv
  shell: |
    git clone https://github.com/wfarr/goenv.git ~/.goenv
    ## add goenv env
    mkdir ~/.go
    mkdir ~/.go/bin
    (
        echo 'export GOENV_ROOT=~/.goenv'
        echo 'export PATH=$GOENV_ROOT/bin:$PATH'
        echo 'export GOPATH=~/.go'
        echo 'export PATH=$GOPATH/bin:$PATH'
        echo 'eval "$(goenv init -)"'
        echo ''
    ) >> ~/.bashrc
    source ~/.bashrc
    goenv install {{golang.version}}
    goenv global {{golang.version}}
