- name: install tools
  yum: pkg={{ item }} state=installed
  with_items:
     - jq
     - telnet
     - ack
     - tcpdump
     - iperf
     - tmux

- name: install axel
  yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/a/axel-2.4-9.el7.x86_64.rpm state=present

- name: install q
  yum: name=https://github.com/harelba/packages-for-q/raw/master/rpms/q-text-as-data-1.5.0-1.noarch.rpm state=present

# aws-tooks
- name: install aws tools
  become: no
  pip: name={{ item }}
  with_items:
    - awscli
    - aws-shell

# mysql
- name: add mysql repo
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm state=present

- name: install mysql-community-server
  yum: name=mysql-community-server state=installed

# peco
- name: copy peco install.sh
  copy: src=peco.sh dest=/tmp/peco.sh mode=0755

- name: install peco
  become: yes
  shell: sh /tmp/peco.sh

# z
- name: install z command
  shell: |
    git clone https://github.com/rupa/z /tmp/z
    mv /tmp/z/z.sh /usr/local/bin/z.sh
    chmod 755 /usr/local/bin/z.sh

# ghq
- name: install ghq
  become: no
  shell: |
    go get github.com/motemen/ghq

# dropbox
# @see http://qiita.com/yudoufu/items/163f9c9b6b9fa2f4bf9e
- name: install dropbox daemon
  become: no
  shell: |
    cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -

- name: install dropbox command
  get_url:
    url: https://www.dropbox.com/download?dl=packages/dropbox.py
    dest: /usr/local/bin/dropbox.py
    mode: 0755
