name             'developkit'
maintainer       'spc'
maintainer_email 'smdmts@gmail.com'
license          'All rights reserved'
description      'Installs/Configures developkit'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'rbenv'
depends 'golang'
depends 'scala'
depends 'nodejs'
